name: getcure_doctor
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  moor: ^3.1.0
  moor_ffi: ^0.8.0 
  path_provider: ^1.5.0
  path: ^1.6.4
  font_awesome_flutter: ^8.10.0
  data_connection_checker: ^0.3.4
  http:
  mime:
  progress_dialog:
  rounded_loading_button: ^1.0.6
  search_widget: ^1.0.2
  flutter_syntax_view:
  image_picker: ^0.6.7+2
  sqflite: ^1.1.3 
  loading: ^1.0.2
  dio: ^3.0.9
  shared_preferences: ^0.5.7+2
  provider: ^4.1.3
  pin_code_fields: ^3.0.0
  date_field: ^0.1.2
  autocomplete_textfield: ^1.7.3
  flutter_datetime_picker: ^1.3.8
  flutter_holo_date_picker: ^0.1.4
  multiselect_formfield: ^0.1.3
  flutter_icons: ^1.1.0
  fluttertoast: ^7.1.1
  modal_progress_hud: ^0.1.3
  flutter_html_to_pdf: ^0.5.2
  flutter_full_pdf_viewer: ^1.0.2
  searchable_dropdown: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.0
  json_serializable: ^3.3.0
  moor_generator: ^3.1.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/.
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
